# Generated by Django 6.0.2 on 2026-03-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopecasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopecast',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
