# Generated by Django 6.0.2 on 2026-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopecasts', '0002_hopecast_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopecast',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hopecast',
            name='verse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
