# Generated by Django 6.0.2 on 2026-03-07 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopecasts', '0003_hopecast_name_hopecast_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopecastPlayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('hopecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_logs', to='hopecasts.hopecast')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
