# Generated by Django 6.0.2 on 2026-02-28 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('ANXIETY_FEAR', 'Anxiety & Fear'), ('HEALTH', 'Health'), ('FINANCE', 'Finance'), ('RELATIONSHIP', 'Relationship'), ('OTHER', 'Other')], default='GENERAL', max_length=50)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('share_first_name', models.BooleanField(default=True)),
                ('wants_follow_up', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('PRAYED', 'Prayed'), ('COMPLETED', 'Completed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
