# Generated by Django 6.0.2 on 2026-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayer',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ON_PROGRESS', 'On Progress'), ('COMPLETED', 'Completed')], default='NEW', max_length=20),
        ),
    ]
