server {
    listen 80;
    server_name api.hopebegins.today;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        alias /var/www/hopebeginbackend/staticfiles/;
    }

    location /media/ {
        alias /var/www/hopebeginbackend/media/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/hopebeginbackend/app.sock;
    }

    # SSL configuration will be added by certbot later
}
