# Generated by Django 6.0.2 on 2026-03-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_hope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopejourney',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hopejourney',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
