# Generated by Django 6.0.2 on 2026-03-30 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_hope', '0002_hopejourney_finished_at_hopejourney_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopefulBeginningCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hopeful Beginning Completion',
                'verbose_name_plural': 'Hopeful Beginning Completions',
            },
        ),
    ]
