# Generated by Django 6.0.2 on 2026-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_hope', '0003_hopefulbeginningcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['day_number'],
            },
        ),
    ]
