# Generated by Django 6.0.2 on 2026-05-06 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HopeStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('testimonial', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='hope_stories/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hope Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
