# Generated by Django 6.0.2 on 2026-05-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A Word for You', max_length=255)),
                ('description', models.TextField(default='Before anything else, we want you to hear this.')),
                ('video_embed_url', models.URLField(default='https://www.youtube.com/embed/zHPaFDRZMUo?rel=0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journey Content',
                'verbose_name_plural': 'Journey Content',
            },
        ),
    ]
